spring:
  application:
    name: luvCocktail

  config:
    import: "classpath:applicationAPI.yml"

  # MySQL 연결 설정
  datasource:
    url: jdbc:mysql://database-1.cls4oq20gmca.ap-northeast-2.rds.amazonaws.com:3306/MonsterDB
    username: admin
    password: admin1013
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa설정
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: none


  logging:
    level:
      org:
        hibernate:
          SQL: debug
          type: trace
server:
  port: 9092
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

